#pragma once
#include <Windows.h>
#include <cstdint>
#include <iostream>
#include <tuple>
#include <Psapi.h>
#include "Structures.hpp"
#include "../bin/resource.h"
#include "defs.hpp"
#include "Utils.hpp"
#include "Injection.hpp"